"""add vector_store_id to chats

Revision ID: d657f0b173dc
Revises: 34debe5b73c5
Create Date: 2026-02-27 14:42:59.042339

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd657f0b173dc'
down_revision = '34debe5b73c5'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.add_column(sa.Column('vector_store_id', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('chats', schema=None) as batch_op:
        batch_op.drop_column('vector_store_id')

    # ### end Alembic commands ###
